Repository FRONT-END-BOOTCAMP-PLUS-5/ONNS, pull requests merged in 2025-07, with the labels that each got.

#12 feat: button 컴포넌트
  app/components/Button.tsx
  public/assets/icons/right.svg
Labels: feat

#15 feat: prtest
  app/components/Header.tsx
  public/assets/icons/logo.svg
Labels: feat

#21 feat: props추가 및 text 색상, 크기 수정
  app/components/Nav.tsx
Labels: feat, fix

#39 게시글 생성 api
  (backend)/api/home/route.ts
  (backend)/api/my/route.ts
  (backend)/api/ootd/route.ts
  (backend)/api/user/route.ts
  (backend)/ootd/application/usecases/CreateUseCase.tsx
  (backend)/ootd/domain/entities/Board.tsx
  (backend)/ootd/domain/repositories/IBoradRepository.tsx
  (backend)/ootd/infrastructure/repositories/SbBoardRepositories.tsx
  .github/workflows/build-check.yml
  app/api/ootd/route.ts
Labels: BE

#43 feat: 게시글 조회 api 완료
  (backend)/ootd/application/usecases/GetPostUseCase.tsx
  app/api/ootd/route.ts
Labels: feat, BE

#45 마이페이지 API 및 JWT Cookie 조회
  (backend)/home/application/usecases/.gitkeep
  (backend)/home/domain/entities/.gitkeep
  (backend)/home/domain/repositories/.gitkeep
  (backend)/home/infrastructure/repositories/.gitkeep
  (backend)/my/application/usecases/.gitkeep
  (backend)/my/application/usecases/GetUserLikesUseCase.ts
  (backend)/my/application/usecases/GetUserPostsUseCase.ts
  (backend)/my/application/usecases/GetUserUseCase.ts
  (backend)/my/application/usecases/UpdateUserUseCase.ts
  (backend)/my/domain/entities/.gitkeep
  (backend)/my/domain/entities/User.ts
  (backend)/my/domain/repositories/.gitkeep
  (backend)/my/domain/repositories/IUserRepository.ts
  (backend)/my/infrastructure/repositories/.gitkeep
  (backend)/my/infrastructure/repositories/SbUserRepository.ts
  (backend)/ootd/application/usecases/.gitkeep
  (backend)/ootd/domain/entities/.gitkeep
  (backend)/ootd/domain/repositories/.gitkeep
  (backend)/ootd/infrastructure/repositories/.gitkeep
  app/(anon)/my/components/PhotoGrid.tsx
  app/(anon)/my/components/ProfileEditHeader.tsx
  app/(anon)/my/components/ProfileHeader.tsx
  app/(anon)/my/components/ProfileName.tsx
  app/(anon)/my/components/ProfileNameEdit.tsx
  app/(anon)/my/components/ProfilePic.tsx
  app/(anon)/my/components/ProfilePicEdit.tsx
  app/(anon)/my/components/ToggleBar.tsx
  app/(anon)/my/page.tsx
  app/api/my/.gitkeep
  app/api/my/me/likes/route.ts
  app/api/my/me/posts/route.ts
  app/api/my/me/route.ts
  app/components/Nav.tsx
  app/layout.tsx
  next.config.ts
  package.json
  public/assets/icons/edit_pencil.svg
  public/assets/icons/profile_edit.svg
  public/assets/images/test_profile.jpg
  types/svgr.d.ts
  utils/auth/tokenAuth.ts
Labels: feat, BE, FE

#49 feat: 게시글 수정 API
  (backend)/ootd/application/usecases/UpdateUseCase.ts
  (backend)/ootd/infrastructure/repositories/SbBoardRepositories.ts
  app/api/ootd/route.ts
Labels: feat, BE

#53 feat: 로그아웃 보완 및 회원 탈퇴 api 구현
  (backend)/user/application/usecases/KakaoLoginUseCase.ts
  (backend)/user/application/usecases/LogoutUseCase.ts
  (backend)/user/application/usecases/UserDeleteUseCase.ts
  (backend)/user/domain/entities/JWTPayload.ts
  (backend)/user/domain/entities/User.ts
  (backend)/user/domain/repositories/AuthRepository.ts
  (backend)/user/domain/repositories/IAuthRepository.ts
  (backend)/user/domain/repositories/IKakaoAuthService.ts
  (backend)/user/domain/repositories/KakaoAuthService.ts
  (backend)/user/infrastructure/repositories/SbAuthRepository.ts
  (backend)/user/infrastructure/repositories/SbKakaoAuthServiceImpl.ts
  (backend)/user/infrastructure/repositories/SupabaseAuthRepository.ts
  .husky/commit-msg
  .husky/pre-commit
  app/(anon)/auth/callback/CallBack.tsx
  app/(anon)/home/HomeClient.tsx
  app/(anon)/my/page.tsx
  app/api/auth.ts
  app/api/auth/kakao/route.ts
  app/api/auth/route.ts
  app/api/user/.gitkeep
  app/api/user/delete/me/route.ts
  hooks/useAuth.ts
  hooks/useLoginModal.ts
  package.json
  utils/auth/tokenAuth.ts
Labels: feat, BE

#55 feat: 댓글 관리 시스템 구현
  (backend)/comment/application/dtos/CommentDto.ts
  (backend)/comment/application/usecases/DeleteCommentUseCase.ts
  (backend)/comment/application/usecases/GetCommentUseCase.ts
  (backend)/comment/application/usecases/PostCommentUseCase.ts
  (backend)/comment/domain/entities/Comment.ts
  (backend)/comment/domain/repositories/ICommentRepository.ts
  (backend)/comment/infrastructure/mapper/CommentMapper.ts
  (backend)/comment/infrastructure/repositories/SbCommentRepository.ts
  app/api/auth/test/route.ts
  app/api/comment/[id]/route.ts
  app/api/ootd/[id]/comment/route.ts
Labels: feat, BE

#59 fix: jwt토큰 id type수정
  utils/auth/tokenAuth.ts
Labels: fix

#61 fix: 토큰 검증시 이미지 인증 제외
  utils/auth/tokenAuth.ts
Labels: fix

#58 feat: 좋아요 api 구현
  (backend)/likes/application/usecases/GetPostLikesUsecase.ts
  (backend)/likes/application/usecases/PostLikesUsecase.ts
  (backend)/likes/domain/entities/Likes.ts
  (backend)/likes/domain/repositories/ILikesRepository.ts
  (backend)/likes/infrastructure/repositories/SbLikesRepository.ts
  app/api/ootd/[id]/likes/route.ts
Labels: feat, BE

#64 feat: 알람 기능 api 구현
  (backend)/notification/application/dtos/NotificationDto.ts
  (backend)/notification/application/usecases/GetAllNotificationsUseCase.ts
  (backend)/notification/application/usecases/GetUnreadCountUseCase.ts
  (backend)/notification/application/usecases/MarkAsReadUseCase.ts
  (backend)/notification/domain/entities/Notification.ts
  (backend)/notification/domain/repositories/INotiRepository.ts
  (backend)/notification/infrastructure/repositories/SbNotiRepository.ts
  app/api/notification/[id]/read/route.ts
  app/api/notification/route.ts
  app/api/notification/unread/route.ts
Labels: feat, BE

#62 fix: 헤더 컴포넌트 수정
  app/components/Header.tsx
  app/components/HeaderClient.tsx
  app/layout.tsx
  public/assets/icons/back.svg
  public/assets/icons/notification-read.svg
  public/assets/icons/notification_unread.svg
Labels: fix, FE

#76 fix: 모달 닫기 버튼 문제
  hooks/useLoginModal.ts
Labels: fix, FE

#79 온도별 계절 필터
  (backend)/ootd/application/usecases/GetPostUseCase.ts
  (backend)/ootd/application/usecases/SeasonUseCase.ts
  (backend)/ootd/domain/repositories/IBoradRepository.ts
  (backend)/ootd/infrastructure/repositories/SbBoardRepositories.ts
  app/api/ootd/route.ts
Labels: feat, BE

#85 필터들 UI 작업
  app/(anon)/ootd/components/SeasonFlt/OotdSeasonDropdown.tsx
  app/(anon)/ootd/components/SeasonFlt/Season.tsx
  app/(anon)/ootd/components/SeasonFlt/SeasonFilter.tsx
  app/(anon)/ootd/components/SortPost/SortPost.tsx
  app/(anon)/ootd/components/TempFlt/TempFlt.tsx
  app/(anon)/ootd/components/index.ts
  app/(anon)/ootd/page.tsx
  env
  hooks/useDropdown.ts
  public/assets/icons/arrow.svg
Labels: feat, FE

#88 feat: home api added
  (backend)/ootd/application/usecases/GetMostLikedPostsByTempUseCase.ts
  (backend)/ootd/application/usecases/GetPostsUseCase.ts
  (backend)/ootd/application/usecases/GetRandomPostsByTempUseCase.ts
  (backend)/ootd/domain/repositories/IBoradRepository.ts
  (backend)/ootd/infrastructure/repositories/SbBoardRepositories.ts
  app/(anon)/home/HomeClient.tsx
  app/(anon)/home/components/TodayWeatherInfo.tsx
  app/(anon)/home/components/WeatherIndex.tsx
  app/api/posts/route.ts
Labels: feat, fix, BE

#91 fix: geyByid(상세 조회) userid 누락 수정
  (backend)/ootd/application/usecases/GetPostDetailUseCase.ts
  (backend)/ootd/domain/repositories/IBoradRepository.ts
  (backend)/ootd/infrastructure/repositories/SbBoardRepositories.ts
  app/api/posts/[id]/route.ts
Labels: fix, BE

#89 ootd 상세페이지 프론트 연결
  app/(anon)/home/components/WeatherIndex.tsx
  app/(anon)/ootd/[id]/components/CommentBox.tsx
  app/(anon)/ootd/[id]/components/Input.tsx
  app/(anon)/ootd/[id]/components/PostUserInfo.tsx
  app/(anon)/ootd/[id]/page.tsx
  app/components/DeletePostModalContainer.tsx
  public/assets/icons/mini_more.svg
  public/assets/icons/more.svg
  public/assets/icons/send.svg
  public/assets/icons/stroke_comment.svg
  public/assets/icons/stroke_heart.svg
  utils/date/formatDate.ts
Labels: feat, FE

#94 게시글 목록 조회
  (backend)/ootd/application/usecases/GetPostsUseCase.ts
  app/(anon)/ootd/components/OotdPostList.tsx
  app/(anon)/ootd/page.tsx
  app/api/posts/route.ts
  env
  package-lock.json
  package.json
  yarn.lock
Labels: feat, FE

#98 feat: 홈 캐러셀 구현
  app/(anon)/home/HomeClient.tsx
  app/(anon)/home/components/HomeCarousel.tsx
  app/(anon)/ootd/[id]/page.tsx
  next.config.ts
  package-lock.json
  package.json
  public/assets/images/1.jpg
  public/assets/images/2.jpg
  public/assets/images/3.jpg
  public/assets/images/4.jpg
  public/assets/images/5.jpg
  public/assets/images/6.jpg
  types/posts.ts
  yarn.lock
Labels: feat, FE

#106 feat: 홈 ootd top8 조회 연결
  app/(anon)/home/HomeClient.tsx
  app/(anon)/home/components/HomeCarousel.tsx
  app/(anon)/home/components/TopPosts.tsx
  app/(anon)/ootd/[id]/components/CommentBox.tsx
  app/(anon)/ootd/[id]/components/Input.tsx
  app/(anon)/ootd/[id]/components/PostUserInfo.tsx
  app/(anon)/ootd/[id]/page.tsx
  app/components/Button.tsx
  public/assets/images/1.jpg
  public/assets/images/2.jpg
  public/assets/images/3.jpg
  public/assets/images/4.jpg
  public/assets/images/5.jpg
  public/assets/images/6.jpg
Labels: feat, FE

#107 feat: ootd 작성페이지 연결
  app/(anon)/ootd/write/page.tsx
  app/api/posts/route.ts
  app/components/Button.tsx
  next.config.ts
  public/assets/icons/img_more.svg
Labels: feat, FE

#93 feat: 웹페이지 버전 문구 추가
  app/globals.css
  app/layout.tsx
  public/assets/icons/icon_logo.svg
  public/fonts/BMJUA.ttf
Labels: style, FE

#112 Feat my posts
  (backend)/my/application/usecases/GetUserLikesUseCase.ts
  (backend)/my/application/usecases/GetUserPostsUseCase.ts
  (backend)/my/domain/repositories/IUserRepository.ts
  (backend)/my/infrastructure/repositories/SbUserRepository.ts
  app/(anon)/my/components/PhotoGrid.tsx
  app/(anon)/my/components/ProfileNameEdit.tsx
  app/(anon)/my/components/ProfilePicEdit.tsx
  app/(anon)/my/components/ToggleBar.tsx
  app/(anon)/my/page.tsx
  app/api/users/me/likes/route.ts
  app/api/users/me/posts/route.ts
Labels: feat, BE, FE

#116 feat: 알림 관련 프론트 UI 작업 및 API 연동
  (backend)/notifications/application/usecases/MarkAsReadUseCase.ts
  (backend)/ootd/application/usecases/GetMostLikedPostsByTempUseCase.ts
  (backend)/ootd/application/usecases/GetMostLikedPostsUseCase.ts
  (backend)/ootd/application/usecases/GetPostDetailUseCase.ts
  (backend)/ootd/application/usecases/GetPostsUseCase.ts
  (backend)/ootd/application/usecases/GetRandomPostsByTempUseCase.ts
  (backend)/ootd/application/usecases/GetRandomPostsUseCase.ts
  (backend)/ootd/infrastructure/mapper/BoardMapper.ts
  (backend)/ootd/infrastructure/repositories/SbBoardRepositories.ts
  app/(anon)/home/HomeClient.tsx
  app/(anon)/notification/components/NoticeItem.tsx
  app/(anon)/notification/page.tsx
  app/api/notifications/[id]/read/route.ts
  app/api/notifications/route.ts
  app/api/posts/route.ts
  app/components/Header.tsx
  app/components/HeaderClient.tsx
  lib/formatDate.ts
  lib/truncateText.ts
  public/assets/icons/chat.svg
  public/assets/icons/heart.svg
  stores/authStore.ts
  utils/axiosInstance.ts
Labels: feat, fix, BE, FE

#119 feat: 스타일 및 로딩 수정
  app/(anon)/home/HomeClient.tsx
  app/(anon)/home/components/HomeCarousel.tsx
  app/(anon)/my/page.tsx
  app/(anon)/ootd/[id]/components/PostUserInfo.tsx
  app/(anon)/ootd/[id]/page.tsx
  app/(anon)/ootd/components/OotdPostList.tsx
  public/assets/icons/heart.svg
Labels: refactor, style

#120 feat: 위치 접근 권한 거부 시 fallback 추가
  app/(anon)/home/HomeClient.tsx
  app/components/Toast.tsx
  hooks/useLocation.ts
Labels: feat, FE

#113 fix: ootd 페이지 재접속 시 이전 화면 리랜더링 수정 및 온도별 필터 후 인기순 정렬 전체 인기순 정렬로 변하는 에러 수정
  (backend)/ootd/infrastructure/repositories/SbBoardRepositories.ts
  app/(anon)/ootd/components/OotdPostList.tsx
  app/(anon)/ootd/components/SeasonFlt/OotdSeasonDropdown.tsx
  app/(anon)/ootd/components/SeasonFlt/SeasonFilter.tsx
  app/(anon)/ootd/components/SortPost/SortPost.tsx
  app/(anon)/ootd/components/TempFlt/TempFlt.tsx
  app/(anon)/ootd/page.tsx
Labels: fix, FE

#125 style: 인풋, 버튼 스타일 수정
  app/(anon)/ootd/[id]/components/Input.tsx
  app/(anon)/ootd/write/page.tsx
Labels: style, bug

#127 refactor: api호출 로직 수정
  app/(anon)/ootd/components/OotdPostList.tsx
  app/(anon)/ootd/write/page.tsx
Labels: fix, refactor, FE

#129 fix: ootd 작성 딜레이 수정
  app/(anon)/ootd/write/page.tsx
Labels: style, bug, FE

#130 fix: 비로그인 유저 개인화 페이지 접근 제한 처리
  app/(anon)/home/HomeClient.tsx
  app/components/Header.tsx
  app/components/Nav.tsx
  middleware.ts
Labels: refactor, FE

#133 Feat: readme
  README.md
Labels: docs
